### ISSUE TITLE
Uppy Companion

### ISSUE THREAD

**Issue by Qoraiche** [PHPJunior/mtube#1]
Hello 👋, first thanks for making this repo open-source, my question is how could we configure a companion server with this application in order to have link upload working, I have seen that you hard code a test URL in this file, and it's not configurable:

https://github.com/PHPJunior/mtube/blob/172f46c04f927d12926502e6309b3fa7bc45e529/resources/views/livewire/channel/modal/upload-content.blade.php#L39

**Comment by PHPJunior** [comment]
Sry, my mistake. I forget to remove my test code 😁😁😁. Link upload is not working.. I'm still doing it

**Comment by Qoraiche** [comment]
> Sry, my mistake. I forget to remove my test code 😁😁😁. Link upload is not working.. I'm still doing it

no worries 😉, do you know how could i configure and set up the companion server?

**Comment by Qoraiche** [comment]
Any updates on this?

**Comment by PHPJunior** [comment]
Sry.. It's finished. Currently Im developing Live Stream Feature,  almost done. I will commit it later .  😁😁😁

**Comment by PHPJunior** [comment]
plz clone dev branch

**Comment by Qoraiche** [comment]
Okey thanks, I'm just asking if you ever been able to setup companion server on your local machine (i'm using ubuntu 20) would be great if you can give me installation steps as the documentation steps didn't work for me
